#!/bin/bash
ICONS=(
  "play_arrow"
  "pause"
  "skip_next"
  "skip_previous"
  "volume_up"
  "volume_down"
  "volume_mute"
  "volume_off"
  "mic"
  "mic_off"
  "wifi"
  "bluetooth"
  "battery_full"
  "battery_6_bar"
  "battery_5_bar"
  "battery_4_bar"
  "battery_3_bar"
  "battery_2_bar"
  "battery_1_bar"
  "battery_0_bar"
  "battery_charging_full"
  "battery_charging_90"
  "battery_charging_80"
  "battery_charging_60"
  "battery_charging_50"
  "battery_charging_30"
  "battery_charging_20"
  "battery_alert"
  "bolt"
  "close"
  "error"
  "memory"
  "hard_drive"
  "notifications"
  "notifications_off"
  "search"
  "wallpaper"
  "apps"
  "mouse"
  "auto_awesome"
)

for icon in "${ICONS[@]}"; do
  wget -q -O "/home/yogesh/.config/quickshell/assets/icons/${icon}.svg" "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/${icon}/materialsymbolsrounded/${icon}_48px.svg"
  if [ -s "/home/yogesh/.config/quickshell/assets/icons/${icon}.svg" ]; then
    echo "Downloaded ${icon}.svg"
  else
    echo "Failed ${icon}.svg"
    rm "/home/yogesh/.config/quickshell/assets/icons/${icon}.svg"
  fi
done
