#!/usr/bin/env python3
import os
import sys
import json
import subprocess

CONFIG_DIR = os.path.expanduser("~/.config/quickshell")
NOTCH_CONFIG_FILE = os.path.join(CONFIG_DIR, "notch_settings.json")
HYPR_CONFIG_FILE = os.path.expanduser("~/.config/hypr/quickshell_hypr.lua")

def main():
    if os.environ.get("QUICKSHELL_SANDBOX") == "1":
        print(json.dumps({"status": "sandbox_mode_skipped_apply"}))
        sys.exit(0)

    if len(sys.argv) < 2:
        print(json.dumps({"error": "No JSON payload provided"}))
        sys.exit(1)

    try:
        payload = json.loads(sys.argv[1])
    except Exception as e:
        print(json.dumps({"error": f"Invalid JSON: {e}"}))
        sys.exit(1)

    notch_data = payload.get("notch", {})
    hypr_data = payload.get("hypr", {})

    # 1. ATOMIC WRITE FOR NOTCH SETTINGS
    os.makedirs(CONFIG_DIR, exist_ok=True)
    existing_notch = {}
    if os.path.isfile(NOTCH_CONFIG_FILE):
        try:
            with open(NOTCH_CONFIG_FILE, "r", encoding="utf-8") as fp:
                existing_notch = json.load(fp)
        except Exception:
            pass

    existing_notch.update(notch_data)
    with open(NOTCH_CONFIG_FILE, "w", encoding="utf-8") as fp:
        json.dump(existing_notch, fp, indent=2)

    # 2. WRITE HYPRLAND LUA CONFIG & APPLY VIA HYPRCTL RELOAD
    gaps_in = hypr_data.get("gaps_in", 5)
    gaps_out = hypr_data.get("gaps_out", 10)
    rounding = hypr_data.get("rounding", 10)
    border_size = hypr_data.get("border_size", 2)
    blur_enabled = hypr_data.get("blur", True)
    layout = hypr_data.get("layout", "dwindle")
    animations = hypr_data.get("animations", True)
    active_op = hypr_data.get("active_opacity", 1.0)
    inactive_op = hypr_data.get("inactive_opacity", 1.0)
    shadow = hypr_data.get("shadow", True)
    shadow_range = hypr_data.get("shadow_range", 4)
    dim_inactive = hypr_data.get("dim_inactive", False)
    master_ratio = hypr_data.get("master_ratio", 0.55)
    blur_passes = hypr_data.get("blur_passes", 3)
    blur_size = hypr_data.get("blur_size", 8)
    input_sensitivity = hypr_data.get("input_sensitivity", 0.0)
    input_tap_to_click = hypr_data.get("input_tap_to_click", False)
    input_natural_scroll = hypr_data.get("input_natural_scroll", False)

    os.makedirs(os.path.dirname(HYPR_CONFIG_FILE), exist_ok=True)
    lua_content = f"""-- Generated by Quickshell Settings
hl.config({{
    input = {{
        sensitivity = {input_sensitivity},
        touchpad = {{
            tap_to_click = {str(input_tap_to_click).lower()},
            natural_scroll = {str(input_natural_scroll).lower()}
        }}
    }},
    general = {{
        gaps_in = {gaps_in},
        gaps_out = {gaps_out},
        border_size = {border_size},
        layout = "{layout}"
    }},
    decoration = {{
        rounding = {rounding},
        active_opacity = {active_op},
        inactive_opacity = {inactive_op},
        dim_inactive = {str(dim_inactive).lower()},
        blur = {{
            enabled = {str(blur_enabled).lower()},
            size = {blur_size},
            passes = {blur_passes}
        }},
        shadow = {{
            enabled = {str(shadow).lower()},
            range = {shadow_range}
        }}
    }},
    animations = {{
        enabled = {str(animations).lower()}
    }},
    master = {{
        mfact = {master_ratio}
    }}
}})
"""
    with open(HYPR_CONFIG_FILE, "w", encoding="utf-8") as fp:
        fp.write(lua_content)

    # 3. WRITE HYPRLAND CONF CONFIG
    conf_content = f"""# Generated by Quickshell Settings
input {{
    sensitivity = {input_sensitivity}
    touchpad {{
        tap-to-click = {str(input_tap_to_click).lower()}
        natural_scroll = {str(input_natural_scroll).lower()}
    }}
}}

general {{
    gaps_in = {gaps_in}
    gaps_out = {gaps_out}
    border_size = {border_size}
    layout = {layout}
}}

decoration {{
    rounding = {rounding}
    active_opacity = {active_op}
    inactive_opacity = {inactive_op}
    dim_inactive = {str(dim_inactive).lower()}

    blur {{
        enabled = {str(blur_enabled).lower()}
        size = {blur_size}
        passes = {blur_passes}
    }}

    shadow {{
        enabled = {str(shadow).lower()}
        range = {shadow_range}
    }}
}}

animations {{
    enabled = {str(animations).lower()}
}}

master {{
    mfact = {master_ratio}
}}
"""
    conf_path = os.path.join(os.path.dirname(HYPR_CONFIG_FILE), "quickshell_hypr.conf")
    with open(conf_path, "w", encoding="utf-8") as fp:
        fp.write(conf_content)

    # Apply live to Hyprland
    try:
        subprocess.run(["hyprctl", "reload"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass

    print(json.dumps({"status": "ok"}))

if __name__ == "__main__":
    main()
