#!/usr/bin/env python3
import os
import json
import sys

CACHE_FILE = os.path.expanduser("~/.cache/quickshell/hypr_state.json")
LUA_PATH = os.path.expanduser("~/.config/hypr/quickshell_hypr.lua")
CONF_PATH = os.path.expanduser("~/.config/hypr/quickshell_hypr.conf")
MAIN_LUA = os.path.expanduser("~/.config/hypr/hyprland.lua")
MAIN_CONF = os.path.expanduser("~/.config/hypr/hyprland.conf")

DEFAULTS = {
    "gaps_in": 5, "gaps_out": 10, "rounding": 10, "border_size": 2,
    "shadow_range": 4, "blur_passes": 3, "blur_size": 8,
    "active_opacity": 1.0, "inactive_opacity": 1.0, "master_ratio": 0.55,
    "input_sensitivity": 0.0,
    "blur": True, "animations": True, "shadow": True, "dim_inactive": False,
    "input_tap_to_click": False, "input_natural_scroll": False,
}

def load_state():
    os.makedirs(os.path.dirname(CACHE_FILE), exist_ok=True)
    data = {}
    if os.path.isfile(CACHE_FILE):
        try:
            with open(CACHE_FILE, "r") as fp:
                data = json.load(fp)
        except Exception:
            pass
    return data

def save_state(data):
    with open(CACHE_FILE, "w") as fp:
        json.dump(data, fp)

def convert_type(t, v):
    if t in ["gaps_in", "gaps_out", "rounding", "border_size", "shadow_range", "blur_passes", "blur_size"]:
        return int(v)
    elif t in ["active_opacity", "inactive_opacity", "master_ratio", "input_sensitivity"]:
        return float(v)
    elif t in ["blur", "animations", "shadow", "dim_inactive", "input_tap_to_click", "input_natural_scroll"]:
        return v.lower() == "true"
    return v

def generate_lua(data):
    return f'''-- Generated by Top Notch Bar (Permanent Hyprland Configuration Overrides)
hl.config({{
    input = {{
        sensitivity = {data.get("input_sensitivity", DEFAULTS["input_sensitivity"])},
        touchpad = {{
            tap_to_click = {"true" if data.get("input_tap_to_click", DEFAULTS["input_tap_to_click"]) else "false"},
            natural_scroll = {"true" if data.get("input_natural_scroll", DEFAULTS["input_natural_scroll"]) else "false"}
        }}
    }},
    general = {{
        gaps_in = {data.get("gaps_in", DEFAULTS["gaps_in"])},
        gaps_out = {data.get("gaps_out", DEFAULTS["gaps_out"])},
        border_size = {data.get("border_size", DEFAULTS["border_size"])},
        layout = "{data.get("layout", "dwindle")}",
        col = {{
            active_border = "{data.get("active_border", "rgba(0a84ffff)")}",
            inactive_border = "{data.get("inactive_border", "rgba(585b70ff)")}"
        }}
    }},
    decoration = {{
        rounding = {data.get("rounding", DEFAULTS["rounding"])},
        active_opacity = {data.get("active_opacity", DEFAULTS["active_opacity"])},
        inactive_opacity = {data.get("inactive_opacity", DEFAULTS["inactive_opacity"])},
        shadow = {{ 
            enabled = {"true" if data.get("shadow", DEFAULTS["shadow"]) else "false"},
            range = {data.get("shadow_range", DEFAULTS["shadow_range"])}
        }},
        dim_inactive = {"true" if data.get("dim_inactive", DEFAULTS["dim_inactive"]) else "false"},
        blur = {{ 
            enabled = {"true" if data.get("blur", DEFAULTS["blur"]) else "false"},
            size = {data.get("blur_size", DEFAULTS["blur_size"])},
            passes = {data.get("blur_passes", DEFAULTS["blur_passes"])}
        }}
    }},
    animations = {{ enabled = {"true" if data.get("animations", DEFAULTS["animations"]) else "false"} }},
    master = {{ mfact = {data.get("master_ratio", DEFAULTS["master_ratio"])} }}
}})
'''

def generate_conf(data):
    return f'''# Generated by Top Notch Bar (Permanent Hyprland Configuration Overrides)
input {{
    sensitivity = {data.get("input_sensitivity", DEFAULTS["input_sensitivity"])}
    touchpad {{
        tap-to-click = {"true" if data.get("input_tap_to_click", DEFAULTS["input_tap_to_click"]) else "false"}
        natural_scroll = {"true" if data.get("input_natural_scroll", DEFAULTS["input_natural_scroll"]) else "false"}
    }}
}}

general {{
    gaps_in = {data.get("gaps_in", DEFAULTS["gaps_in"])}
    gaps_out = {data.get("gaps_out", DEFAULTS["gaps_out"])}
    border_size = {data.get("border_size", DEFAULTS["border_size"])}
    layout = {data.get("layout", "dwindle")}
    col.active_border = {data.get("active_border", "rgba(0a84ffff)")}
    col.inactive_border = {data.get("inactive_border", "rgba(585b70ff)")}
}}

decoration {{
    rounding = {data.get("rounding", DEFAULTS["rounding"])}
    active_opacity = {data.get("active_opacity", DEFAULTS["active_opacity"])}
    inactive_opacity = {data.get("inactive_opacity", DEFAULTS["inactive_opacity"])}
    dim_inactive = {"true" if data.get("dim_inactive", DEFAULTS["dim_inactive"]) else "false"}

    blur {{
        enabled = {"true" if data.get("blur", DEFAULTS["blur"]) else "false"}
        size = {data.get("blur_size", DEFAULTS["blur_size"])}
        passes = {data.get("blur_passes", DEFAULTS["blur_passes"])}
    }}

    shadow {{
        enabled = {"true" if data.get("shadow", DEFAULTS["shadow"]) else "false"}
        range = {data.get("shadow_range", DEFAULTS["shadow_range"])}
    }}
}}

animations {{
    enabled = {"true" if data.get("animations", DEFAULTS["animations"]) else "false"}
}}

master {{
    mfact = {data.get("master_ratio", DEFAULTS["master_ratio"])}
}}
'''

def ensure_includes(data, script_include, conf_source):
    if os.path.isfile(MAIN_LUA):
        with open(MAIN_LUA, "r", encoding="utf-8") as fp:
            content = fp.read()
        if "quickshell_hypr.lua" not in content:
            with open(MAIN_LUA, "a", encoding="utf-8") as fp:
                fp.write("\n\n-- Include Top Notch Bar Permanent Config\n" + script_include + "\n")

    if os.path.isfile(MAIN_CONF):
        with open(MAIN_CONF, "r", encoding="utf-8") as fp:
            content = fp.read()
        if "quickshell_hypr.conf" not in content:
            with open(MAIN_CONF, "a", encoding="utf-8") as fp:
                fp.write("\n\n# Include Top Notch Bar Permanent Config\n" + conf_source + "\n")

def update_and_persist(typ, val):
    data = load_state()
    data[typ] = convert_type(typ, val)
    save_state(data)

    with open(LUA_PATH, "w", encoding="utf-8") as fp:
        fp.write(generate_lua(data))

    with open(CONF_PATH, "w", encoding="utf-8") as fp:
        fp.write(generate_conf(data))

    ensure_includes(
        data,
        'pcall(dofile, os.getenv("HOME") .. "/.config/hypr/quickshell_hypr.lua")',
        'source = $HOME/.config/hypr/quickshell_hypr.conf'
    )

def update_with_data(data):
    save_state(data)
    with open(LUA_PATH, "w", encoding="utf-8") as fp:
        fp.write(generate_lua(data))
    with open(CONF_PATH, "w", encoding="utf-8") as fp:
        fp.write(generate_conf(data))

if __name__ == "__main__":
    if len(sys.argv) >= 3:
        update_and_persist(sys.argv[1], sys.argv[2])
        print("ok")
    else:
        print("Usage: persist_hypr_state.py <type> <value>")
        sys.exit(1)
